mindless/mindless/urls.py
from django.contrib import admin
from django.urls import path

from hci import views

urlpatterns = [
    path('', views.participant_selection),
    path('<int:ppntid>/', views.study_introduction, name='study-introduction'),
    path('<int:ppntid>/survey/', views.study_survey, name='study-survey'),
    path('<int:ppntid>/practice/', views.stage_task, {'is_practice': True}, name='practice-task'),
    path('<int:ppntid>/stage/<int:stgid>/', views.stage_introduction, name='stage-introduction'),
    path('<int:ppntid>/stage/<int:stgid>/task/', views.stage_task, name='stage-task'),
    path('<int:ppntid>/stage/<int:stgid>/survey/', views.stage_survey, name='stage-survey'),
    path('<int:ppntid>/stage/<int:stgid>/conclusion/', views.stage_conclusion, name='stage-conclusion'),
    path('<int:ppntid>/conclusion/', views.study_conclusion, name='study-conclusion'),
    path('admin/', admin.site.urls),
]

mindless/hci/models.py
from django.db import models
from django.db.models import Count
from django.urls import reverse


class Participant(models.Model):
    first_names = models.CharField(max_length=50, blank=False, null=False)
    last_name = models.CharField(max_length=50, blank=False, null=False)
    participant_id = models.PositiveSmallIntegerField('Participant ID', primary_key=True)
    is_control = models.BooleanField('Control participant', default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def ranking(self):
        aggregate = Participant.objects.filter(created_at__lt=self.created_at).aggregate(ranking=Count('created_at'))
        return aggregate['ranking'] + 1

    class Meta:
        ordering = ('participant_id',)

    def __str__(self):
        return f'{self.first_names} {self.last_name} ({self.participant_id})'

    def get_next_link(self):
        completed_stage_count = self.stagetaskresult_set.count()
        if not hasattr(self, 'studysurvey'):
            return reverse('study-introduction', args=(self.participant_id,))

        if completed_stage_count < 3:
            return reverse('stage-introduction', args=(self.participant_id, completed_stage_count + 1))

        return None


meditation_choices = [
    ('none', 'Not at all'), ('less_1_week', 'Less than once per week'), ('1_3_week', '1-3 times per week'),
    ('4_7_week', '4-7 times per week'), ('multiple_day', 'Multiple times per day')]
mindfulness_choices = [('0', 'Not at all'), ('1', 'Partially'), ('2', 'Reasonably'), ('3', 'Thoroughly')]
gender_choices = [('m', 'Male'), ('f', 'Female'), ('custom', 'Specify')]
age_bracket_choices = [('20_under', '20 or under'), ('21_23', '21-23'), ('24_27', '24-27'), ('28_plus', '28+')]
meditation_tech_choices = [('never', 'Never'), ('sometimes', 'Sometimes'), ('always', 'Always')]


class StudySurvey(models.Model):
    participant = models.OneToOneField(Participant, models.CASCADE, primary_key=True)
    gender = models.CharField(max_length=10, choices=gender_choices, verbose_name='What is your gender?', default=None)
    custom_gender = models.CharField(max_length=50, blank=True, verbose_name='My gender')
    age_bracket = models.CharField(max_length=50, choices=age_bracket_choices, verbose_name='How old are you?',
                                   default=None)
    mindfulness = models.CharField(max_length=50, choices=mindfulness_choices,
                                   verbose_name='How well do you believe you understand mindfulness?', default=None)
    meditation = models.CharField(max_length=50, choices=meditation_choices, verbose_name='How often do you meditate?',
                                  default=None)
    meditation_tech = models.CharField(max_length=50, choices=meditation_tech_choices,
                                       verbose_name='Do you use technology to meditate?',
                                       default=meditation_tech_choices[0])

    def __str__(self):
        return str(self.participant)


class Stage(models.Model):
    identifier = models.PositiveSmallIntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.TextField()

    class Meta:
        ordering = ('identifier',)

    def __str__(self):
        return f'Stage {self.identifier} ({self.name})'


class StageTaskResult(models.Model):
    participant = models.ForeignKey(Participant, models.CASCADE)
    stage = models.ForeignKey(Stage, models.CASCADE)
    result = models.TextField()

    class Meta:
        unique_together = (('participant', 'stage'),)
        ordering = ('participant', 'stage',)

    def __str__(self):
        return f'Stage {self.stage.identifier} / Participant {self.participant.participant_id}'


class SurveyQuestion(models.Model):
    identifier = models.PositiveSmallIntegerField()
    question = models.TextField()

    class Meta:
        ordering = ('identifier',)

    def __str__(self):
        return f'Question {self.identifier}'


class SurveyAnswer(models.Model):
    question = models.ForeignKey(SurveyQuestion, models.CASCADE)
    participant = models.ForeignKey(Participant, models.CASCADE)
    answer = models.TextField()
    stage = models.ForeignKey(Stage, models.CASCADE)

    class Meta:
        unique_together = (('question', 'stage', 'participant'),)
        ordering = ('participant', 'stage', 'question',)

    def __str__(self):
        return f'Stage {self.stage.identifier} / Question {self.question.identifier} / Participant {self.participant.participant_id}'

mindless/hci/forms.py
from django import forms

from hci.models import Participant, StudySurvey


class ParticipantForm(forms.Form):
    participant = forms.ModelChoiceField(Participant.objects.all())


class StudySurveyForm(forms.ModelForm):
    class Meta:
        model = StudySurvey
        exclude = ['participant']
        widgets = {
            'gender': forms.RadioSelect,
            'age_bracket': forms.RadioSelect,
            'mindfulness': forms.RadioSelect,
            'meditation': forms.RadioSelect,
            'meditation_tech': forms.RadioSelect,
        }

mindless/hci/views.py
import json

from django.shortcuts import render, redirect
from django.urls import reverse

from hci.decorators import add_ppnt_stg
from hci.forms import StudySurveyForm
from hci.models import Participant, Stage, StageTaskResult, SurveyQuestion, SurveyAnswer
from hci.utils import participator


def participant_selection(r):
    pending_ppnts = [ppnt for ppnt in Participant.objects.all() if ppnt.get_next_link()]
    finished_ppnts = [ppnt for ppnt in Participant.objects.all() if not ppnt.get_next_link()]
    ctx = {'pending_ppnts': pending_ppnts, 'finished_ppnts': finished_ppnts}
    return render(r, 'hci/participant_selection.html', ctx)


@add_ppnt_stg
def study_introduction(r, *args, **kwargs):
    ctx = args[0]
    ctx['stages'] = [(stg_num + 1, Stage.objects.get(pk=stg_id)) for stg_num, stg_id in
                     enumerate([participator.get_stage(ctx['ppnt'].participant_id, stg_no + 1) for stg_no in range(3)])]
    return render(r, 'hci/study_introduction.html', ctx)


@add_ppnt_stg
def study_survey(r, *args, **kwargs):
    ctx = args[0]
    if r.method == 'POST':
        form = StudySurveyForm(r.POST)
        if form.is_valid():
            survey = form.save(commit=False)
            survey.participant = ctx['ppnt']
            survey.save()
            return redirect('stage-introduction', kwargs['ppntid'], Stage.objects.first().identifier)
        else:
            ctx['form'] = form
            return render(r, 'hci/study_survey.html', ctx)

    ctx['form'] = StudySurveyForm()
    return render(r, 'hci/study_survey.html', ctx)


@add_ppnt_stg
def stage_introduction(r, *args, **kwargs):
    return render(r, 'hci/stage_introduction.html', args[0])


@add_ppnt_stg
def stage_task(r, *args, **kwargs):
    ctx = args[0]
    is_practice = kwargs.get('is_practice', False)
    if r.method == 'POST':
        clicker_data = r.POST['clicker-data']
        filler_data = r.POST['filler-data']
        if is_practice and clicker_data and filler_data:
            return redirect('stage-introduction', kwargs['ppntid'], 1)
        elif not is_practice and clicker_data and filler_data:
            json_string = {'clicker': json.loads(clicker_data), "filler": json.loads(filler_data)}
            combined_json = json.dumps(json_string)
            StageTaskResult.objects.update_or_create(defaults={'result': combined_json}, participant=ctx['ppnt'],
                                                     stage=ctx['stage'])
            return redirect('stage-conclusion' if ctx['ppnt'].is_control else 'stage-survey', kwargs['ppntid'],
                            kwargs['stgid'])

    ctx['is_practice'] = is_practice
    return render(r, 'hci/stage_task.html', ctx)


@add_ppnt_stg
def stage_survey(r, *args, **kwargs):
    ctx = args[0]
    all_questions = SurveyQuestion.objects.all()

    if r.method == 'POST':
        all_answered = all([f'qtn-{q.identifier}' in r.POST for q in all_questions])
        if all_answered:
            for question in all_questions:
                SurveyAnswer.objects.update_or_create(question=question, participant=ctx['ppnt'], stage=ctx['stage'],
                                                      defaults={'answer': r.POST[f'qtn-{question.identifier}']})
            return redirect('stage-conclusion', kwargs['ppntid'], kwargs['stgid']) if kwargs['stgid'] < 3 else redirect(
                'study-conclusion', kwargs['ppntid'])

    ctx['answers'] = [
        {'label': 'Strongly disagree', 'value': 1},
        {'label': 'Disagree', 'value': 2},
        {'label': 'Slightly disagree', 'value': 3},
        {'label': 'Slightly agree', 'value': 4},
        {'label': 'Agree', 'value': 5},
        {'label': 'Strongly agree', 'value': 6},
    ]
    ctx['all_questions'] = all_questions
    return render(r, 'hci/stage_survey.html', ctx)


@add_ppnt_stg
def stage_conclusion(r, *args, **kwargs):
    if kwargs['stgid'] == Stage.objects.last().identifier:
        return redirect('study-conclusion', kwargs['ppntid'])

    ctx = args[0]
    ctx['next_link'] = reverse('stage-introduction', args=(kwargs['ppntid'], kwargs['stgid'] + 1))
    return render(r, 'hci/stage_conclusion.html', ctx)


@add_ppnt_stg
def study_conclusion(r, *args, **kwargs):
    return render(r, 'hci/study_conclusion.html', args[0])

mindless/templates/hci/_conclusion.html
<div class="mt-2 mb-2">
    <canvas id="cloud-canvas" width="640" height="480">Your browser doesn't support canvas elements, and can't
        show this pretty picture.
    </canvas>
</div>
{% if all_done %}
    <p><b>Please do not close this window.</b></p>
{% else %}
    <p>Click <em>Next Stage</em> to continue.</p>
    <a href="{{ next_link }}" class="btn btn-primary">Next Stage</a>
{% endif %}
<div class="text-muted mt-5">

    <ul>
        <li>
            <small>
                <a href="http://opengameart.org/content/fluffy-clouds">Fluffy Clouds</a> by <a
                    href="http://daniel.benoy.name/">Daniel Gregory Benoy</a> under <a
                    href="http://www.gnu.org/licenses/gpl-2.0.html">GNU GPL 2.0</a>/<a
                    href="http://www.gnu.org/licenses/gpl-3.0.html">GNU GPL 3.0</a>/<a
                    href="http://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA 3.0</a> license.
            </small>
        </li>
        <li>
            <small>
                Background tiles by <a href="http://silveiraneto.net">silveira neto</a>. See the <a
                    href="https://github.com/silveira/openpixels">Open Pixels project</a>. <a
                    href="http://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA 3.0</a> license.
            </small>
        </li>
        <li>
            <small>Code by <a href="http://silveiraneto.net">silveira neto</a> under <a
                    href="http://www.gnu.org/licenses/gpl-3.0.html">GNU GPL 3.0</a> or <a
                    href="http://creativecommons.org/licenses/by-sa/3.0/">CC-BY-SA 3.0</a> license.
            </small>
        </li>
    </ul>
</div>

mindless/templates/hci/participant_selection.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}

{% block title %}Participant Selection{% endblock %}
{% block subtitle %}Mindfulness Study Evaluation{% endblock %}

{% block content %}
    {% for ppnt in pending_ppnts %}
        <a class="btn btn-primary"
           href="{{ ppnt.get_next_link }}">{{ ppnt }}</a>
    {% endfor %}

    {% if finished_ppnts %}
        <h5 class="mt-4">Finished Participants</h5>
        {% for ppnt in finished_ppnts %}
            <button class="btn btn-default" disabled>{{ ppnt }}</button>
        {% endfor %}
    {% endif %}
{% endblock %}

{% block page_icon %}<img class="page-icon" src="{% static 'hci/img/select-user.svg' %}">{% endblock %}

mindless/templates/hci/stage_conclusion.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}
{% load hci_extras %}

{% block title %}
    {% if ppnt.is_control %}
        Stage {{ stage_disp }}
    {% else %}
        {% stage_title %}
    {% endif %}
{% endblock %}
{% block subtitle %}Stage Complete{% endblock %}

{% block content %}
    <p>You have now completed stage {{ stage_disp }} of 3. Thank you for your
        participation up to this point!</p>
    {% include 'hci/_conclusion.html' with all_done=False %}
{% endblock %}

{% block bootstrap4_extra_script %}
    <script src="{% static 'hci/js/forest.js' %}"></script>
{% endblock %}

{% block page_icon %}<img class="page-icon" src="{% static 'hci/img/checkmark.svg' %}">{% endblock %}

mindless/templates/hci/stage_introduction.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}
{% load hci_extras %}

{% block title %}
    {% if ppnt.is_control %}
        Stage {{ stage_disp }}
    {% else %}
        {% stage_title %}
    {% endif %}
{% endblock %}
{% block subtitle %}Introduction{% endblock %}

{% block content %}
    {% if ppnt.is_control %}
        <p>Before undergoing tasks to test your multitasking ability, we ask that you wait for 5 minutes to ensure that
            no undesirable bias affects this study's results. During this time, we ask that you do what you normally
            would in your free time.</p>
        <div id="countdown" class="my-4"></div>
    {% else %}
        <p>{{ stage.description }}</p>
    {% endif %}

    <p class="continue {% if ppnt.is_control %}d-none{% endif %}">When you're ready to begin, click <em>
        {% if ppnt.is_control %}Continue{% else %}Done With App{% endif %}</em>.
    </p>
    <a class="btn btn-primary continue {% if ppnt.is_control %}disabled{% endif %}"
       href="{% url 'stage-task' ppnt.participant_id stage_disp %}">
        {% if ppnt.is_control %}Continue{% else %}Done With App{% endif %}</a>

{% endblock %}

{% block page_icon %}<img class="page-icon" src="{% static 'hci/img/phone.svg' %}">{% endblock %}

{% if ppnt.is_control %}
    {% block bootstrap4_extra_script %}
        <script src="{% static 'hci/js/jquery.progressBarTimer.min.js' %}"></script>
        <script type="application/javascript">
            $("#countdown").progressBarTimer({
                timeLimit: 300,
                warningThreshold: 5,
                autostart: true,
                onFinish: function () {
                    $('.continue').removeClass('d-none').removeClass('disabled');
                }
            }).start()
        </script>
    {% endblock %}
{% endif %}

mindless/templates/hci/stage_survey.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}
{% load hci_extras %}

{% block title %}{% stage_title %}{% endblock %}
{% block subtitle %}Survey{% endblock %}

{% block content %}
    <p>You will now be presented with statements shown below. For each statement, choose the option which you believe
        most accurately represents your experience in this stage. This will give us a useful indication of the
        effectiveness of the mindfulness apps used.</p>

    <form method="post" id="survey-form">
        {% csrf_token %}
        {% for question in all_questions %}
            <h5>Statement {{ question.identifier }}</h5>
            <p>{{ question.question }}</p>
            <div class="mb-4">
                <div class="btn-group btn-group-toggle" data-toggle="buttons">
                {% for answer in answers %}
                    <label class="btn btn-light">
                        <input type="radio" name="qtn-{{ question.identifier }}" value="{{ answer.value }}" autocomplete="off"> {{ answer.label }}
                    </label>
                {% endfor %}
                </div>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary" disabled>Submit</button>
    </form>

{% endblock %}

{% block bootstrap4_extra_script %}
<script>
$('#survey-form input[type=radio]').change(() => {
    let isFormValid = true;
    $('#survey-form .btn-group').each((i, g) => {
        if (!$(g).find('input:checked').length) {
            isFormValid = false;
            return false;
        }
    });
    $('#survey-form button[type=submit]').attr('disabled', !isFormValid)
});
</script>
{% endblock %}

{% block page_icon %}<img class="page-icon" src="{% static 'hci/img/survey.svg' %}">{% endblock %}

mindless/templates/hci/stage_task.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}
{% load hci_extras %}

{% block title %}
    {% if is_practice %}
        Before We Begin
    {% else %}
        {% if ppnt.is_control %}
            Stage {{ stage_disp }}
        {% else %}
            {% stage_title %}
        {% endif %}
    {% endif %}
{% endblock %}
{% block subtitle %}Task
    {% if is_practice %}
        <span class="badge badge-info">Practice</span>
    {% else %}
        <span class="badge badge-warning">Recorded</span>
    {% endif %}
{% endblock %}

{% block content %}
    {% if is_practice %}
        <div class="card">
            <div class="card-body">
                <p>A task consists of two games: <em>Clicker</em> and <em>Filler</em>, which are explained below. These
                    games will test the effect of mindfulness apps on your ability to multitask.
                    This practice round is <b>not recorded</b>, and is shorter than the (following)
                    recorded
                    task.</p>
                <p>These
                    games have <b>no time limit</b>, and you may work on either game at any time. A game will become
                    brighter when
                    your cursor is over the game window, and will become slightly transparent when your cursor leaves
                    the
                    game window.</p>
            </div>
        </div>
        <div class="row mt-2">
            <div class="col-6">

                <div class="card">
                    <div class="card-body"><h5><img class="task-type-icon"
                                                    src="{% static 'hci/img/fill.svg' %}"> Filler</h5>
                        <p>In this exercise, you are to drag shapes on
                            the
                            left to
                            exactly fill the map on the right.</p>
                        <p>Screens are completed by filling the map with all available shapes. If a shape does
                            not belong where
                            you drag it onto the map, it will nudge itself to appear misaligned with the map, indicating
                            that the
                            shape has been improperly placed.</p></div>
                </div>
            </div>

            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"><img class="task-type-icon" src="{% static 'hci/img/click.svg' %}">
                            Clicker
                        </h5>
                        <p>In this exercise, you are to click the
                            appropriate shape depending on the guide shown at the top of the clicker window. The left
                            guide
                            shows
                            what to click with the <em>left</em> mouse button, while the right guide indicates that of
                            the
                            <em>right</em> mouse button.</p>
                        <p>If both a square and a circle are shown for one mouse button, you are to click any shape of
                            <em>that
                                guide's colour</em>. Alternatively, if <em>one shape</em> is shown in each guide, you
                            are to
                            click only
                            the guide's shape with the corresponding mouse button, but can click shapes of any colour.
                        </p>
                        <p>Screens are completed by correctly clicking all shapes such that none are
                            left.</p>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <div class="row mt-2">
        <div class="col-6">
            <canvas width="512" height="480" id="filler" class="game-canvas"></canvas>
        </div>
        <div class="col-6">
            <canvas width="512" height="480" id="clicker" class="game-canvas"></canvas>
        </div>
    </div>

    <form method="POST" id="stage-task-form">
        <input id="clicker-data" name="clicker-data" type="hidden">
        <input id="filler-data" name="filler-data" type="hidden">
        {% if is_practice %}
            <input id="is-practice" name="is-practice" value="true" type="hidden">
        {% endif %}
        {% csrf_token %}
        <button type="submit" class="mt-4 btn btn-primary" id="task-submit" disabled>Complete {% if is_practice %}
            Practice {% endif %}Task
        </button>
        <p id="task-submit-text" class="text-muted">
            <small>You cannot complete this task until both exercises have been finished.</small>
        </p>
    </form>
{% endblock %}

{% block bootstrap4_extra_script %}
    <script type="module" src="{% static 'hci/js/easing.js' %}"></script>
    <script type="module" src="{% static 'hci/js/clicker.js' %}"></script>
    <script src="{% static 'hci/js/filler.js' %}"></script>
    <script type="application/javascript">
        $('#clicker-data, #filler-data').change(() => {
            if ($('#clicker-data').val().length && $('#filler-data').val().length) {
                $('#task-submit').attr('disabled', false);
                $('#task-submit-text').hide();
            }
        });
    </script>
{% endblock %}

{% block page_icon %}<img class="page-icon" src="{% static 'hci/img/game.svg' %}">{% endblock %}

mindless/templates/hci/study_conclusion.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load humanize %}
{% load staticfiles %}

{% block title %}Study Conclusion{% endblock %}
{% block subtitle %}Study Complete!{% endblock %}

{% block content %}
    <p>Thank you for your participation in this study. You have now completed all stages, and you are
        finished! We appreciate your time.</p>
    {% include 'hci/_conclusion.html' with all_done=True %}
{% endblock %}

{% block bootstrap4_extra_script %}
    <script src="{% static 'hci/js/forest.js' %}"></script>
{% endblock %}

{% block page_icon %}<img class="page-icon" src="{% static 'hci/img/finish-flag.svg' %}">{% endblock %}

mindless/templates/hci/study_introduction.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}

{% block title %}Welcome, {{ ppnt }}{% endblock %}
{% block subtitle %}Mindfulness Study Evaluation{% endblock %}

{% block content %}
    <p>In this study, you will be asked to make use of a mindfulness app for a short period of time. Following this, we
        will ask you to play a mini-game.</p>
    <p>This study is broken down into three stages. You will be asked to take a short break between each
        stage.</p>
    {% if not ppnt.is_control %}
        <ul class="list-group">
            {% for stg_num, stage in stages %}
                <li class="list-group-item">Stage {{ stg_num }} ({{ stage.name }})</li>
            {% endfor %}
        </ul>
    {% endif %}

    <p class="mt-4">When you're ready to begin, click <em>Continue</em>.</p>
    <a class="btn btn-primary" href="{% url 'study-survey' ppnt.participant_id %}">Continue</a>
{% endblock %}

{% block page_icon %}<img class="page-icon" src="{% static 'hci/img/study.svg' %}">{% endblock %}

mindless/templates/hci/study_survey.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load staticfiles %}

{% block title %}Before We Begin{% endblock %}
{% block subtitle %}Pre-Study Survey{% endblock %}

{% block content %}
    {#    {{ form.errors }}#}
    <form method="post" id="form-study-survey">
        {% csrf_token %}
        <input type="hidden" name="participant_id" value="{{ ppnt.participant_id }}">
        {% bootstrap_form form %}
        {% bootstrap_button 'Submit Survey' button_type='submit' button_class='btn-primary' %}
    </form>
{% endblock %}

{% block page_icon %}<img class="page-icon" src="{% static 'hci/img/survey.svg' %}">{% endblock %}

{% block bootstrap4_extra_script %}
    <script type="application/javascript">
        const custom_gender_group = $('#id_custom_gender').parent();
        custom_gender_group.hide();
        $('input[type=radio][name="gender"]').change(function () {
            if (this.value === 'custom') {
                custom_gender_group.show();
            } else {
                custom_gender_group.hide();
            }
        });

        const meditation_tech_group = $('#id_meditation_tech_0').parent().parent().parent();
        meditation_tech_group.hide();
        $('input[type=radio][name="meditation"]').change(function () {
            if (this.value !== 'none') {
                meditation_tech_group.show();
            } else {
                meditation_tech_group.hide();
            }
        });
    </script>
{% endblock %}